### ISSUE TITLE
Sampling type of get_logits

### ISSUE THREAD

**Issue by Opdoop** [rabeehk/vibert#11]
Hi, the `sampling_type` in `get_logits` makes me confuse. 
https://github.com/rabeehk/vibert/blob/c2e7aa3f81ff9a73eb112739e284cb98b6fa2de4/models.py#L63-L71
It seems that in training stage `sampling_type` is the default `iid` but changes to `argmax` in evaluation.
Why do we need these two different sampling types?

**Comment by rabeehk** [comment]
Hi there,
during the training, you would add these noises to make the train the model with z, and make it robust towards these variations, in the test time, you would use the expected value. This is the conventional way of training the variational models.

**Comment by Opdoop** [comment]
Ohhh! Thanks for your rapid response! I never expect to get a response like using SMS!
And thanks for your careful explanation. It solves my confusion! You really saved my day! 🤗
