### ISSUE TITLE
Parameters for other cases / datasets

### ISSUE THREAD

**Issue by yassouali** [rabeehk/vibert#4]
Hi,

Thank you for the paper & the provided code.

I was wondering if it is possible to provide the optimal parameters for the different experiments in the paper, specifically, does the parameters (K & beta) change for each different number of samples & glue task, or do they remain the same as in the example script, the same question for the OOD results.

I also observed that the results are very sensitive to K, is this is really the case or just in my case (using RoBERTa instead of BERT)?

Thank you.

**Comment by rabeehk** [comment]
Hi @yassouali 
sorry for my delayed response, I had two deadlines this week.

>> does the parameters (K & beta) change for each different number of samples & glue task, or do they remain the same as in the example script, the same question for the OOD results.

Yes, I tune the parameters given the range mentioned in the paper for each experiment, and in most of the results I reported average across 3 seeds. I also tuned the parameters for each seed, by finding the setting resulting in the maximum validation performance.

>> I also observed that the results are very sensitive to K, is this is really the case or just in my case (using RoBERTa instead of BERT)?
Yes, to my experience, compared to \beta, K had more impact, so one perhaps can reduce the options for beta to be able to try more options for K

I looked into the files, here are the numbers I could find for 1 seed, I hope this could help, but I remember I reported the average across 3 seeds in most of the cases. Also to choose  the epoch, as explained in the paper, I run for a max epoch and then find the epoch with maximum validation, and report the test result corresponding to that epoch. 

```
\\ hyperparameters for out of domain results 
\begin{table}[b]
    \centering
    %\resizebox{0.5\textwidth}{!}{
    \begin{tabular}{lllll}
        \toprule 
        & \multicolumn{2}{c}{\textbf{SNLI}} & \multicolumn{2}{c}{\textbf{MNLI}} \\ 
         \cmidrule(r){2-3} \cmidrule(l){4-5} 
        {\vspace{-0.75em} \textbf{Data}} &  \multicolumn{2}{c}{} & \multicolumn{2}{c}{}\\ 
                 & \textbf{K} & \bm{$\beta$} & \textbf{K} & \bm{$\beta$}\\
        \toprule  
        SICK &  48&1e-5 & 36 & 1e-5 \\
        ADD1  &12& 1e-4& 24&1e-5 \\
        DPR  &192&1e-5 &48&1e-4 \\
        SPR &48&1e-5&144&1e-5\\
        FN+  &192&1e-5 &36&1e-5  \\
        JOCI & 72&1e-5&36&1e-5\\
        MPE  &48&1e-5& 12&1e-5\\
        SCITAIL&36&1e-4 & 24&1e-4 \\
        QQP  & 12&1e-4&72&1e-4\\
        \midrule 
        SNLI Hard & 48&1e-4 &384&1e-4\\ % copied from SNLI.
        \midrule 
        SNLI  &48&1e-4 &384&1e-4\\
        MNLI-M &72&1e-4 &384&1e-5\\
        MNLI &48 & 1e-4&384&1e-5\\
    \bottomrule
    \end{tabular}%}
 \caption{Hyper-parameters used to report the results of the out-of-domain generalization experiment.}
\end{table}

\\ hyperparameters for subsampled results. 
\begin{table}[H]
\centering
%\resizebox{0.5\textwidth}{!}{%
\begin{tabular}{lcccccccccccccc}
\toprule
\textbf{Hyper-parameters} & \textbf{200} & \textbf{500} & \textbf{800}   & \textbf{1000}  & \textbf{3000}   & \textbf{6000} \\ 
\midrule 
\multicolumn{7}{c}{\textbf{Dataset:} \snli}  \\  
\midrule 
K & 48 & 192  & 48  & 192 & 384  & 48  \\ 
$\beta$  & 1e-5 & 1e-5 &1e-5 & 1e-4 & 1e-5 & 1e-4\\ 
\midrule 
\multicolumn{7}{c}{\textbf{Dataset:} \mnli}  \\  
\midrule 
K & 36 & 24  & 48  & 36  & 288 & 384 \\ 
$\beta$  & 1e-5 & 1e-5 & 1e-4 & 1e-4 & 1e-5 & 1e-5 \\ 
\midrule 
\multicolumn{7}{c}{\textbf{Dataset:} \imdb}  \\  
\midrule 
K & 288 & 48  & 192  & 36 & 384 & 18 \\ 
$\beta$  &1e-4 & 1e-4 & 1e-4 & 1e-4 & 1e-4 & 1e-5\\ 
\midrule 
\multicolumn{7}{c}{\textbf{Dataset:} \yelp}  \\  
\midrule 
K & 72 &  72 & 384  & 384 & 384 & 96 \\ 
$\beta$  &1e-4 & 1e-4 & 1e-5 & 1e-5 & 1e-5 & 1e-5\\ 
\bottomrule 
\end{tabular}%}
\caption{Hyper-parameters used to report the results of the VIB method.}
\label{tab:low-resource-params} 
\end{table} 


\\ hyper-parameter for the results on GLUE for bert-base 
 \textbf{Hyper-parameters} & \mrpc & \stsb & \rte  \\
 K     &  288 & 192 & 192 \\ 
 $\beta$         & 1e-6  & 1e-5 & 1e-6 \\ 
 epoch          & 3 & 4 & 5 \\ 
```
Best regards
Rabeeh

**Comment by yassouali** [comment]
Thank you @rabeehk
