### ISSUE TITLE
MNLI-Hard and MNLI-M hard dataset

### ISSUE THREAD

**Issue by neerajkuhike** [rabeehk/vibert#5]
Hi, 

MultiNLI,MNLIMatched,MNLIMismatched, MNLIMismatchedHard, MNLIMatchedHard,MNLITrueMismatched, MNLITrueMatched,MNLIMatchedHardWithHardTest,MNLIMismatchedHardWithHardTest

Among these dataset , which dataset you have used as MNLI-Hard and MNLI-M hard dataset

**Comment by rabeehk** [comment]
Dear @neerajkuhike 
I have trained the models on MNLI mismatched dataset, and then evaluate them on the original MNLI(-M) hard sets, please find the test datasets here 

https://www.kaggle.com/c/multinli-matched-open-hard-evaluation/
https://www.kaggle.com/c/multinli-mismatched-open-hard-evaluation/
