### ISSUE TITLE
Analysis of the Removed Features

### ISSUE THREAD

**Issue by neerajkuhike** [rabeehk/vibert#6]
Hi ,

Can you just explain to me the procedure of the experiment 'Analysis of the Removed Features'.

What I understood is as follows:
Step 1- Train the model with bert pre-train embedding .
step2- Freeze all the layers except the classifier layer(last layer) to see the accuracy which will prove the hypothesis.

What is the sample size . I am assuming seeing the results. It is 200. 

Please correct me if I am wrong.

Can you tell me

**Comment by rabeehk** [comment]
Hi
could you share your email with me, so I send you the codes?
thanks

**Comment by neerajkuhike** [comment]
Hi ,


My email id is - neerajkr2k14@gmail.com.

Thanks
