### ISSUE TITLE
Memory requirement

### ISSUE THREAD

**Issue by neerajkuhike** [rabeehk/vibert#8]
Hi ,

How are you calculating the memory requirement for the model.
I am using the below code and getting a larger value than that is proposed in the paper.    

mem_params = sum([param.nelement()*param.element_size() for param in model.parameters()])
    mem_bufs = sum([buf.nelement()*buf.element_size() for buf in model.buffers()])
    mem = mem_params + mem_bufs # in bytes
    
    print(mem/(1024*1024))

**Comment by rabeehk** [comment]
Hi there,
Here is how I computed it:

    if torch.cuda.is_available() and args.memory_outputfile:

        peak_memory = torch.cuda.max_memory_allocated()/1024**2

        print(

            "Memory utilization",

            peak_memory,

            "MB"

        )

        memory_usage = {"peak_memory": peak_memory}


Best
Rabeeh

**Comment by rabeehk** [comment]
Hi there,
Here is how I computed it:
```
    if torch.cuda.is_available():
        peak_memory = torch.cuda.max_memory_allocated()/1024**2
        print(
            "Memory utilization",
            peak_memory,
            "MB"
        )
        memory_usage = {"peak_memory": peak_memory}
```

Best
Rabeeh
