### ISSUE TITLE
the way about estimating mu_p and std_p

### ISSUE THREAD

**Issue by ShellingFord221** [rabeehk/vibert#9]
Hi, in `kl_div` function of `models.py`, you compute the KL divergence of estimated distribution and true distribution. But true distribution is parameterized by `self.mu_p` and `self.std_p`, which are two parameters defined in `__init__` of class `BertForSequenceClassification`. On the other hand, estimated distribution is parameterized by `mean` and `std`, which are two outputs of the model. Then how to minimize KL divergence of two distributions both in change? Will loss of this part converge? Thanks!

**Comment by ShellingFord221** [comment]
It seems that in [Alemi et al. (2017)](https://arxiv.org/pdf/1612.00410.pdf), the prior r(z) is assumed to be a standard normal distribution:

> Finally, we treat r(z) as a fixed K-dimensional spherical Gaussian, r(z) = N (z|0, I).

However, in your code, r(z) is parameterized by
https://github.com/rabeehk/vibert/blob/c2e7aa3f81ff9a73eb112739e284cb98b6fa2de4/models.py#L31
and
https://github.com/rabeehk/vibert/blob/c2e7aa3f81ff9a73eb112739e284cb98b6fa2de4/models.py#L32

Seems that your implementation is more reasonable, since prior of latent factor could be any Gaussian distribution. But how to optimize parameters of prior and make sure that training process can converge? Thanks！

**Comment by rabeehk** [comment]
Dear @ShellingFord221 
Please accept my apologies for the late response. About the two distribution, since both are Gaussian, one can optimize the loss in a closed form, please see footnote 2 on page 3 of the paper.

As you said in Alemi's code they consider a fixed mu and std, I experimented with this version as well, as I observed if we make them variables, since it would have more flexibility, it can learn a better distribution.

**Comment by ShellingFord221** [comment]
Hi, thanks for the reply! I notice that footnote 2 is the formula to calculate KL divergence of two Gaussian distributions, in which \mu_0 and \sigma_0 are the parameters of prior r(z) and \mu_1 and \sigma_1 can be considered as the parameters of posterior p(z|x). In your codes, \mu_1 and \sigma_1 are the outputs of our model while \mu_0 and \sigma_0 are set to be variables rather than fixed values (i.e. 0 and 1). I wonder when gradients back-propagates, should we first fix \mu_0 and \sigma_0 to optimize the model according to its outputs \mu_1 and \sigma_1, then fix the model to optimize prior \mu_0 and \sigma_0, or just optimize them simultaneously? I don't know whether the training process can converge if both two distributions are changeable. Thanks!

**Comment by rabeehk** [comment]
Hi
we optimize them jointly as done in the codes and this was able to converge to our experience.
